version: "3.3"

services:

  selenium:
    image: selenium/standalone-chrome:latest
    restart: always
    ports:
      - "7900:7900"
      - "4444:4444"
    privileged: true
    shm_size: 4g
    environment:
      - SE_NODE_MAX_SESSIONS=5