spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/story_library
    username: postgres
    password: fS4FR4s0M5J&HcB1j0P%
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
      maximum-pool-size: 30

app:
  configs:
    storiesPageLimit: 99999999

  web-driver:
    pool:
      storyListing:
        maxSize: 1
        headless: true
        remoteUrl: http://selenium:4444/wd/hub
      storyDetail:
        maxSize: 3
        headless: true
        remoteUrl: http://selenium:4444/wd/hub

  jsoup-executor:
    pool:
      storyListing:
        maxSize: 1
      storyDetail:
        maxSize: 2

  schedules:
    jobs-creation:
      stories-crawling:
        # every 4 hours of every day
        cron: 0 0 */4 * * ?
        disabled: false
      story-crawling:
        # every hour of every day
        cron: 0 0 * * * ?
        disabled: false
      chapters-crawling:
        # every 10 minutes
        cron: 0 */10 * * * ?
        disabled: false

    jobs-bootstrap:
      stories-crawling:
        # every 5 minutes
        cron: 0 2/5 * * * ?
        disabled: false
      story-crawling:
        # every 5 minutes
        cron: 0 1/3 * * * ?
        disabled: false
      chapters-crawling:
        # every 3 minutes
        cron: 0 0/3 * * * ?
        disabled: false

  basic-auth:
    users:
      - username: Admin
        # Admin@12345677
        password: "$2a$10$tLrYxE7PjTpc5vESWu1SxefNuQhCgvm.iuNsGMsQhtg3i6rfzMwri"
        roles: "Admin"

  metruyencv:
    accounts:
      - username: xuankhanhyb@gmail.com
        password: Xuankhanh93a@
      - username: quangkhoiii01@gmail.com
        password: 1234567890

  bunny-net:
    base-url: https://sg.storage.bunnycdn.com
    api-key: 92465016-edd9-4147-8fa37ed0d440-b39f-4e6d
    storage-zone-name: story-library
    story-thumbnail-folder: thumbnails